export { default as Home } from './Home'
export { default as Product } from './Product'
export { default as Shop } from './Shop'
export { default as Cart } from './Cart'
export { default as Checkout } from './Checkout'
export {default as Payment} from './Payment'